# Usamos una imagen de Node 20 basada en Alpine Linux por su ligereza
FROM node:24

# Habilitamos corepack para poder usar pnpm (incluido en Node.js)
# Habilita pnpm
RUN corepack enable

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app
